export const COUNTRIES = [
  { code: "AR", name: "Argentina" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "CZ", name: "Czechia" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IT", name: "Italy" },
  { code: "JP", name: "Japan" },
  { code: "MY", name: "Malaysia" },
  { code: "NL", name: "Netherlands" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "ES", name: "Spain" },
  { code: "TH", name: "Thailand" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "IN", name: "India" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "ZA", name: "South Africa" },
  { code: "TR", name: "Turkey" },
  { code: "CO", name: "Colombia" },
  { code: "BR", name: "Brazil" },
  { code: "BE", name: "Belgium" },
  { code: "TR", name: "Turkey" },
  { code: "CO", name: "Colombia" },
  { code: "BR", name: "Brazil" },
];
